name-template: 'Release {version}'
tag-template: '$NEXT_MINOR_VERSION'
template: |
  ## Release Notes for {version}
  $CHANGES


# name-template: 'Release {version}'
# tag-template: '$VERSION'
# template: |
#   ## Minor Release Notes for {version}
  
#   **Release Date:** $RELEASE_DATE
  
#   ### 🛠 Breaking Changes
#   $BREAKING_CHANGES
  
#   ### 🎉 New Features
#   $FEATURES
  
#   ### 🐛 Fixes
#   $FIXES
  
#   ### 🔄 Improvements
#   $IMPROVEMENTS
  
#   ### 📜 Other Changes
#   $OTHER_CHANGES
  
#   ### 🙏 Thanks to Contributors
#   $CONTRIBUTORS

# categories:
#   - title: Breaking Changes 🛠
#     labels:
#       - breaking-change
#   - title: New Features 🎉
#     labels:
#       - feature
#   - title: Fixes 🐛
#     labels:
#       - bug
#       - fix
#   - title: Other Changes
#     labels:
#       - "*"
